export { default as Apple } from './Apple.jpg';
export { default as Cherry } from './Cherry.jpg';
export { default as Graph } from './Graph.jpg';
export { default as HanRA } from './HanRA.jpg';
export { default as Kiwi } from './Kiwi.jpg';
export { default as Persimmon } from './Persimmon.jpg';
export { default as PineApple } from './PineApple.jpg';
export { default as SetMenuImg } from './SetMenuImg.jpg';
export { default as Tomato } from './Tomato.jpg';
